# Generated by Django 5.1.4 on 2025-01-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0001_initial'),
        ('AppTwo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books_published',
            field=models.ManyToManyField(related_name='authors', to='AppOne.book'),
        ),
    ]
